blank_issues_enabled: true
contact_links:
  - name: Contributing Guide
    url: https://github.com/wra-sol/awesome-canada/blob/master/CONTRIBUTING.md
    about: Please read the contributing guidelines before submitting a resource suggestion or a pull request.
